### DISCUSSION TITLE
v1.0.11

### DISCUSSION THREAD

**Discussion by xfhg** [xfhg/intercept#176] [Announcements]
![interceptv1](https://github.com/user-attachments/assets/52a33f90-ed17-4f7d-855d-6625659cb373)

## Release v1.0.11

- github actions integration + compliant output (examples provided)
- performance optimizations / core binaries updated
- hooks signatures and auth options 
- remote policy execution endpoint :

## Remote Policy Execution Endpoint

1. Add your user public keys to the policy file : 
```yaml
Config: 
  Flags:
    remote_auth:
      - "UserA:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICtFRLdSvayFQwQdIOk6NKuEpEK7KvYBQz8LUVerSo8T"
      - "UserB:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJyubt40tutUSi3FQqcEzbDUu14RdLstEbURvX/M2bM/"
```
2. Run your observe command with --remote (can use the example test_remote.yaml on the playground)
3. SSH into your intercept instance with one of your IDs (in remote_auth) on port 23234
4. ???
5. Profit

![INTERCEPT-v1 0 11](https://github.com/user-attachments/assets/84a248db-9c54-419f-8835-19bc5f4f2ab8)

## What's Changed
* Integration/GitHub by @xfhg in https://github.com/xfhg/intercept/pull/174
* Updated Docs by @xfhg in https://github.com/xfhg/intercept/pull/172
* Core/remote by @xfhg in https://github.com/xfhg/intercept/pull/175

--- 

**Full Changelog**: https://github.com/xfhg/intercept/compare/v1.0.10...v1.0.11

<hr /><em>This discussion was created from the release <a href='https://github.com/xfhg/intercept/releases/tag/v1.0.11'>v1.0.11</a>.</em>
